
export const LIST_ACTION = {
  ADD_ITEM: 'ADD_ITEM',
  SELECT_ITEM: 'SELECT_ITEM',
  DELETE_SELECTED: 'DELETE_SELECTED',
  UNDO: 'UNDO',
} as const;

export const MODAL_ACTION = {
  MODAL_OPEN: 'MODAL_OPEN',
  MODAL_REQUEST_CLOSE: 'MODAL_REQUEST_CLOSE',
  MODAL_ANIMATION_END: 'MODAL_ANIMATION_END',
} as const;
